[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
harness = false

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
embedded-graphics = "0.8.1"
uefi = "0.35.0"
x86_64 = "0.15.2"
uefi_kernel = { path = ".." }
xmas-elf = "0.10.0"
