[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bootloader"
harness = false

[dependencies]
log = "0.4.27"
uefi = { version = "0.35.0", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
xmas-elf = "0.10.0"
